apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/tricky42/argocd-jobtest.git'
    path: argocd
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
