apiVersion: batch/v1
kind: Job
metadata:
  generateName: loop-
  annotations:
    compare-options: IgnoreExtraneous
    sync-options: Prune=false
spec:
  template:
    spec:
      containers:
      - name: jobby
        image: k3d-localhost:5111/jobby
        command: ["bash", "/script.sh"]
      restartPolicy: Never
  backoffLimit: 4
